ERROR = 'ERROR'
SERVER_ERROR = 'SERVER_ERROR %s'
CLIENT_ERROR = 'CLIENT_ERROR %s'

STORED = 'STORED'
NOT_FOUND = 'NOT_FOUND'
NOT_STORED = 'NOT_STORED'
DELETED = 'DELETED'
OK = 'OK'

VALUE_FORMAT = 'VALUE %(key)s %(flags)d %(length)d\r\n%(data)s\r\n'
VALUE_END = 'END'
